### ISSUE TITLE
incompatibility with sprockets-rails 2.1.3 (wrong number of arguments (2 for 1) in stylesheet_link_tag)

### ISSUE THREAD

**Issue by monfresh** [schneems/sprockets_better_errors#22]
`sprockets_better_errors` doesn't seem to play well with `sprockets-rails` 2.1.3.

I recently upgraded Rails from 4.0.4 to 4.0.8, which also upgraded `sprockets-rails` from 2.0.1 to 2.1.3. After this upgrade, when I tried to visit my app in development, I got the stack trace below, and the first line came from sprockets_better_errors. Removing the `sprockets_better_errors` gem solved the issue, as did keeping the gem, but locking `sprockets-rails` at 2.0.1.

```
ArgumentError - wrong number of arguments (2 for 1):
  sprockets_better_errors (0.0.5) lib/sprockets_better_errors/sprockets_rails_helper.rb:71:in `check_errors_for'
  sprockets-rails (2.1.3) lib/sprockets/rails/helper.rb:156:in `block in stylesheet_link_tag'
  sprockets-rails (2.1.3) lib/sprockets/rails/helper.rb:155:in `map'
  sprockets-rails (2.1.3) lib/sprockets/rails/helper.rb:155:in `stylesheet_link_tag'
  sprockets_better_errors (0.0.5) lib/sprockets_better_errors/sprockets_rails_helper.rb:66:in `stylesheet_link_tag'
  app/views/layouts/application.html.erb:22:in `_app_views_layouts_application_html_erb___3295036906910030958_70136723052580'
  actionpack (4.0.8) lib/action_view/template.rb:143:in `block in render'
  activesupport (4.0.8) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.0.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.0.8) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.0.8) lib/action_view/template.rb:141:in `render'
  actionpack (4.0.8) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  actionpack (4.0.8) lib/action_view/renderer/template_renderer.rb:47:in `render_template'
  actionpack (4.0.8) lib/action_view/renderer/template_renderer.rb:17:in `render'
  actionpack (4.0.8) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionpack (4.0.8) lib/action_view/renderer/renderer.rb:23:in `render'
  actionpack (4.0.8) lib/abstract_controller/rendering.rb:127:in `_render_template'
  actionpack (4.0.8) lib/action_controller/metal/streaming.rb:219:in `_render_template'
  actionpack (4.0.8) lib/abstract_controller/rendering.rb:120:in `render_to_body'
  actionpack (4.0.8) lib/action_controller/metal/rendering.rb:33:in `render_to_body'
  actionpack (4.0.8) lib/action_controller/metal/renderers.rb:26:in `render_to_body'
  actionpack (4.0.8) lib/abstract_controller/rendering.rb:97:in `render'
  actionpack (4.0.8) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.0.8) lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
  activesupport (4.0.8) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/moncef/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
  activesupport (4.0.8) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.0.8) lib/action_controller/metal/instrumentation.rb:41:in `block in render'
  actionpack (4.0.8) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
  actionpack (4.0.8) lib/action_controller/metal/instrumentation.rb:40:in `render'
  actionpack (4.0.8) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (4.0.8) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  actionpack (4.0.8) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.0.8) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.0.8) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (4.0.8) lib/active_support/callbacks.rb:393:in `_run__2604789297523041111__process_action__callbacks'
  activesupport (4.0.8) lib/active_support/callbacks.rb:80:in `run_callbacks'
  actionpack (4.0.8) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (4.0.8) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.0.8) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.0.8) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.0.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.0.8) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.0.8) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.0.8) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  actionpack (4.0.8) lib/abstract_controller/base.rb:136:in `process'
  actionpack (4.0.8) lib/abstract_controller/rendering.rb:44:in `process'
  actionpack (4.0.8) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.0.8) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.0.8) lib/action_controller/metal.rb:231:in `block in action'
  actionpack (4.0.8) lib/action_dispatch/routing/route_set.rb:82:in `call'
  actionpack (4.0.8) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  actionpack (4.0.8) lib/action_dispatch/routing/route_set.rb:50:in `call'
  actionpack (4.0.8) lib/action_dispatch/journey/router.rb:71:in `block in call'
  actionpack (4.0.8) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.0.8) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.0.8) lib/action_dispatch/routing/route_set.rb:676:in `call'
  newrelic_rpm (3.8.1.221) lib/new_relic/rack/error_collector.rb:55:in `call'
  newrelic_rpm (3.8.1.221) lib/new_relic/rack/agent_hooks.rb:32:in `call'
  newrelic_rpm (3.8.1.221) lib/new_relic/rack/browser_monitoring.rb:27:in `call'
  newrelic_rpm (3.8.1.221) lib/new_relic/rack/developer_mode.rb:45:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  actionpack (4.0.8) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.0.8) lib/action_dispatch/middleware/flash.rb:241:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.0.8) lib/action_dispatch/middleware/cookies.rb:486:in `call'
  actionpack (4.0.8) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.0.8) lib/active_support/callbacks.rb:373:in `_run__2154567063475420217__call__callbacks'
  activesupport (4.0.8) lib/active_support/callbacks.rb:80:in `run_callbacks'
  actionpack (4.0.8) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.0.8) lib/action_dispatch/middleware/reloader.rb:64:in `call'
  actionpack (4.0.8) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:56:in `call'
  actionpack (4.0.8) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.0.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.0.8) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.0.8) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.0.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.0.8) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.0.8) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.0.8) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.0.2) lib/quiet_assets.rb:18:in `call_with_quiet_assets'
  actionpack (4.0.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.0.8) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  actionpack (4.0.8) lib/action_dispatch/middleware/static.rb:64:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.0.8) lib/rails/engine.rb:511:in `call'
  railties (4.0.8) lib/rails/application.rb:97:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
  /Users/moncef/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
  /Users/moncef/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
  /Users/moncef/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

**Comment by schneems** [comment]
You are correct, it doesn't work with 2.1.3, so don't use it it's not needed anymore as the changes have been merged into sprockets-rails https://github.com/schneems/sprockets_better_errors/blob/master/sprockets_better_errors.gemspec#L31
