### ISSUE TITLE
Doesn't play nice with Active Admin gem

### ISSUE THREAD

**Issue by mwlang** [schneems/sprockets_better_errors#9]
for Rails 4.0.2 and active-admin master branch, I get an error calling for me to add missing dependencies to the active_admin.scss file.  As I add each one, another comes along, so I assume its going to suggest every single dependency out of the active_admin stylesheets.  I don't see this error when compiling with RAILS_ENV=production rake assets:precompile

```
08:59:48:coming_soon >> rake assets:precompile --trace
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.
** Execute assets:precompile
rake aborted!
Asset depends on 'active_admin/nested_menu_arrow.gif' to generate properly but has not declared the dependency
Please add: `//= depend_on_asset "active_admin/nested_menu_arrow.gif"` to '/Users/mwlang/projects/clients/chaperon/coming_soon/app/assets/stylesheets/active_admin.css.scss'
  (in /Users/mwlang/projects/clients/chaperon/coming_soon/app/assets/stylesheets/active_admin.css.scss)
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets_better_errors-0.0.4/lib/sprockets_better_errors/sprockets_rails_helper.rb:17:in `check_dependencies!'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets_better_errors-0.0.4/lib/sprockets_better_errors/sprockets_rails_helper.rb:22:in `compute_asset_path'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.2/lib/action_view/helpers/asset_url_helper.rb:132:in `asset_path'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.2/lib/action_view/helpers/asset_url_helper.rb:281:in `image_path'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/sass_functions.rb:18:in `image_url'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/script/funcall.rb:113:in `_perform'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/script/node.rb:40:in `perform'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/script/list.rb:71:in `block in _perform'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/script/list.rb:71:in `map'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/script/list.rb:71:in `_perform'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/script/node.rb:40:in `perform'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:298:in `visit_prop'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:53:in `map'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:320:in `visit_rule'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:53:in `map'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:320:in `visit_rule'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:53:in `map'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:320:in `visit_rule'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:53:in `map'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:320:in `visit_rule'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:227:in `block in visit_import'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:227:in `map'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:227:in `visit_import'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:227:in `block in visit_import'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:227:in `map'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:227:in `visit_import'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:53:in `map'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:128:in `visit_root'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/visitors/perform.rb:7:in `visit'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/tree/root_node.rb:20:in `render'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/engine.rb:315:in `_render'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sass-3.2.13/lib/sass/engine.rb:262:in `render'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/sass_template.rb:53:in `evaluate'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/context.rb:197:in `block in evaluate'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/context.rb:194:in `each'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/context.rb:194:in `evaluate'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/processed_asset.rb:12:in `initialize'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/base.rb:374:in `new'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/base.rb:374:in `block in build_asset'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/base.rb:395:in `circular_call_protection'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/base.rb:373:in `build_asset'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/index.rb:94:in `block in build_asset'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/caching.rb:58:in `cache_asset'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/index.rb:93:in `build_asset'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/base.rb:287:in `find_asset'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/index.rb:61:in `find_asset'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/bundled_asset.rb:16:in `initialize'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/base.rb:377:in `new'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/base.rb:377:in `build_asset'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/index.rb:94:in `block in build_asset'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/caching.rb:58:in `cache_asset'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/index.rb:93:in `build_asset'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/base.rb:287:in `find_asset'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/index.rb:61:in `find_asset'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/manifest.rb:211:in `block in find_asset'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/manifest.rb:257:in `benchmark'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/manifest.rb:210:in `find_asset'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/manifest.rb:119:in `block in compile'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/manifest.rb:118:in `each'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/sprockets/manifest.rb:118:in `compile'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-rails-2.0.1/lib/sprockets/rails/task.rb:60:in `block (3 levels) in define'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-2.10.1/lib/rake/sprocketstask.rb:146:in `with_logger'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/sprockets-rails-2.0.1/lib/sprockets/rails/task.rb:59:in `block (2 levels) in define'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.1/lib/rake/task.rb:236:in `call'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.1/lib/rake/task.rb:236:in `block in execute'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.1/lib/rake/task.rb:231:in `each'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.1/lib/rake/task.rb:231:in `execute'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.1/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/Users/mwlang/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.1/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.1/lib/rake/task.rb:161:in `invoke'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.1/lib/rake/application.rb:149:in `invoke_task'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.1/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.1/lib/rake/application.rb:106:in `each'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.1/lib/rake/application.rb:106:in `block in top_level'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.1/lib/rake/application.rb:115:in `run_with_threads'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.1/lib/rake/application.rb:100:in `top_level'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.1/lib/rake/application.rb:78:in `block in run'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.1/lib/rake/application.rb:75:in `run'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.1/bin/rake:33:in `<top (required)>'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/bin/rake:23:in `load'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/bin/rake:23:in `<main>'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `eval'
/Users/mwlang/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => assets:precompile
```

**Comment by schneems** [comment]
This is expected behavior, the way to fix is forking active_admin and adding in all those dependencies If you're a good OSS citizen, i'm sure plenty of people would appreciate a PR back to the project. The reason you're not seeing this in production is this check does not run in production by default. Upgrade to the latest and set 

```
config.assets.raise_production_errors = true
```

In production if you want to see the tests there too.

**Comment by mwlang** [comment]
Ah.  Interesting insight on that.   At least I now have confirmation it really is in the active-admin gem. 

I do try to be a good OSS citizen and contribute to projects as I can.  I'm honestly still having a lot to learn about sprockets in general and getting bit by the "it doesn't work on production but works in development" issue that I've since seen a lot of developers complain about over the last week or so is really my first deep dive into sprockets in general -- in other words, a _lot_ to learn here.
